[workspace]
members = ["programs/nft_minter"]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
nft_minter = "5fGkL4pt8GbmLVzYsZ8PNFY7Xact8H7Wxv5vfRTuSkB1"

[registry]
url = "https://anchor.projectserum.com"
