name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Solana CLI
        run: |
          # Download & unpack the Solana CLI
          curl -sSfL https://release.solana.com/v1.18.3/solana-release-x86_64.tar.bz2 \
            | tar -xj -C $HOME
          # Put the binaries on PATH
          export PATH="$HOME/solana-release/bin:$PATH"
          # Check the version
          solana --version

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked
          avm install latest
          avm use latest
          anchor --version

      - name: Run tests
        run: |
          cd nft_minter
          anchor test --skip-deploy
