name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Solana CLI
        run: |
          # Install via Anza (reliable on GitHub runners)
          sh -c "$(curl -sSfL https://release.anza.xyz/stable/install)"
          # Add it to PATH immediately
          export PATH="$HOME/.local/share/solana/install/active_release/bin:$PATH"
          solana --version

      - name: Install Anchor CLI & SBF toolchain
        run: |
          # Anchor Version Manager
          cargo install --git https://github.com/coral-xyz/anchor avm --locked
          avm install latest
          avm use latest
          anchor --version

          # SBF build support
          rustup component add llvm-tools-preview
          rustup target add bpfel-unknown-unknown
          cargo install cargo-build-sbf

      - name: Run tests
        run: |
          cd nft_minter
          anchor test --skip-deploy

# CI: pulled Solana CLI from GitHub Releases
